### ISSUE TITLE
 How is ‘collaborator’ being defined, and where are the commercial partners?

### ISSUE THREAD

**Issue by BexPerchard** [g4he/g4he#113]
How is ‘collaborator’ being defined? I cannot see on our data any industry/companies listed as collaborators. I think that would be the key intelligence I would be after.

**Comment by richard-jones** [comment]
Ask the ARMA volunteer for some examples with industry partners, so we can investigate how they are being modelled by GtR

**Comment by BexPerchard** [comment]
I have asked for some examples of collaborations with industry partners :)

**Comment by BexPerchard** [comment]
This is the list that Alicen says she sent to Richard, on collaborations with industry partners - I think this would have been a fair while ago?

**Comment by richard-jones** [comment]
Collaborator is being defined dynamically, so this issue is now defunct
