### ISSUE TITLE
return to collaboration report link broken

### ISSUE THREAD

**Issue by BexPerchard** [g4he/g4he#117]
If you click into the project info held on the project name link, the ‘return to Brunel’s collaboration report’ link does not seem to work.  You have to use the back arrow on the browser to return.

**Comment by richard-jones** [comment]
Fixed, though we need to revisit how the project page fits into the reporting environment as a whole.  This means not just being able to go to the collaboration page, but also to go to the benchmarking page, etc.  There is another issue set up to cover this work, so closing here.

see #127
