### ISSUE TITLE
Highlight Collaboration Report

### ISSUE THREAD

**Issue by BexPerchard** [g4he/g4he#118]
There is desire for a report which shows the highlight figures for collaborations (which are what are currently shown in the drop-down on the first draft of the collaboration report).

Would be good to present this as both a table and a bar chart

Based on feedback:

"A suggestion would be to be able to collapse the ‘Collaborators’ and be able to display the number of interactions as a headline figure and then be able to expand into a similar view to the one available (if ordered by Collaborator)."

"Could we have the table as a drillthrough report from a more summarised top level report? The dropdown list to select the collaborator is I would say my preferred top level output of this if it were neatened up to be a table showing all collaborations and"

**Comment by richard-jones** [comment]
Done.
