### ISSUE TITLE
Build a new index

### ISSUE THREAD

**Issue by markmacgillivray** [g4he/g4he#130]
Now that the indexer has been updated, we should build a new index - do not overwrite the current one or any older ones, keep them for later analysis. Make a new index with a new name and update the frontend service to read from the new index endpoint.

Note as per issue #71 that once it is rebuilt we should check the reports still work properly, and fix any references to old keys.

**Comment by richard-jones** [comment]
This is not to be done in Sprint 12 - it will be covered in Sprint 13

**Comment by richard-jones** [comment]
Will now need to take into consideration the new API
