### ISSUE TITLE
Build and optimise a term extraction method

### ISSUE THREAD

**Issue by markmacgillivray** [g4he/g4he#133]
When passed a collection of texts (and perhaps some keywords to start from or to boost), search through them for their keywords. Return the keywords for use elsewhere.

See #129 for the details.

**Comment by richard-jones** [comment]
Preliminary version completed and checked in.  Awaiting feedback on enhancements from @markmacgillivray

**Comment by markmacgillivray** [comment]
Works well. Set up on latest demo. Needs tweaking as we see how it gets used.

**Comment by richard-jones** [comment]
Tested and works well, no further action required
