### ISSUE TITLE
Find out if we can extract person and department data from JeS

### ISSUE THREAD

**Issue by richard-jones** [g4he/g4he#135]
Probably just ask Alicen

**Comment by BexPerchard** [comment]
Emailed Alicen to ask, awaiting response

**Comment by BexPerchard** [comment]
Alicen's colleague Vic has managed to find a way to get a table showing first name, surname, email address, department, account status (active, inactive, suspended). Bex will liaise with Vic to see if we can get access to this spreadsheet

**Comment by BexPerchard** [comment]
Email sent to Vic Gill to see if we can get hold of the spreadsheet

**Comment by BexPerchard** [comment]
Spreadsheet received, with caveat that it is kept confidential

**Comment by BexPerchard** [comment]
Contacted Vic, will let you know her reply!

**Comment by BexPerchard** [comment]
Response from Vic: 

I had to use an unconventional way to extract this data from JeS as it appears that there is no standard function to do this. It’s not difficult though. The account status profiles are quite self-explanatory: ‘active accounts’ are current Brunel staff with active accounts who are or have recently used JeS. Suspended accounts I believe refers to those who have changed roles making them ineligible for a JeS account, left Brunel and in some cases have died.

**Comment by BexPerchard** [comment]
Response from Vic on how she got the data from JeS: 

A JeS Master Account administrator can view a full staff list of all active, inactive and suspended users on one screen. However, whilst the list cannot be printed or exported, it can be copied and pasted into excel and manipulated.

So, the ‘unconventional method’ is nothing but ol’ fashioned copying and pasting.

**Comment by richard-jones** [comment]
No further action - not viable for general usage
