### ISSUE TITLE
Benchmarking feedback - Simon Kerridge @ Leeds 

### ISSUE THREAD

**Issue by BexPerchard** [g4he/g4he#153]
- There is some repeated commentary (on selecting Leeds)
- The total amount does not look good without commas (they have commas later on in the reports)
- Seems strange to be able to compare Leeds with Leeds (it was not selected but looks like it could have been...)
- Can I upload a list of people (eg in excel) that I want to benchmark with rather than having to type and select them

**Comment by richard-jones** [comment]
created/merged into other issues
