### ISSUE TITLE
Benchmarking fb (terminology)  Alicen @ Brunel 

### ISSUE THREAD

**Issue by BexPerchard** [g4he/g4he#157]
-   I assume that ‘projects’ means ‘projects awarded’? Worth being explicit (as with total awarded) for avoidance of any doubt. 
- [When we refer to 'form controls']  I assume you mean comparison options?  Can we compare by institution and funder type somehow?  For example, if I want to compare myself to Bath – can I see if their awards come from Research Councils/Charities/EU etc?  Or, within Research Councils, split by which Research Council?

**Comment by richard-jones** [comment]
Converted/merged into other issues
