### ISSUE TITLE
Improve keyword balance of new potential report

### ISSUE THREAD

**Issue by markmacgillivray** [g4he/g4he#163]

**Comment by markmacgillivray** [comment]
Doing quite well, can't really improve without some more user feedback. So, hand this over to comms to ask people what they think of results, and to ask them to specify where they are getting spurious answers.

**Comment by markmacgillivray** [comment]
Please take to testing group and ask them to use the new potential report in earnest now. Please ask:
- when you provide search terms to match against, do the provisions for choosing terms make sense?
- would you want to provide others sorts of term besides projects, people, keywords and web pages?
- when matches are displayed, do those matches make sense to you? e.g. do the relevant projects that the matched organisation is shown to be involved in make you think that they would indeed be a good match for you?
- when the keywords we used to perform the match are displayed, are they keywords that reflect what you wanted to match against? Are there any particular keywords that seem very out of place?
- any further comments about using the new potential report?

**Comment by BexPerchard** [comment]
Emailed testers with link to screencast + questions
