### ISSUE TITLE
logos confusing, and also distorted - come up with a strategy for how we can use them

### ISSUE THREAD

**Issue by richard-jones** [g4he/g4he#174]
- require permissions to use them (they are trademarked)
- they are distorted, which marketing people will object to
- link to keyword search is confusing

For the time being, logos should be removed, and we should consider how we can achieve the aim of giving a good UI for organisations.  e.g. a "use my logo" checkbox which enables it, or grabs it.

**Comment by markmacgillivray** [comment]
Logos have been removed from the UI.

Passing to Bex Comms for further consideration.

**Comment by richard-jones** [comment]
From mid-sprint meeting
- can take the risk on them on the institutional page
- provide a take-down option/niotice

Leave them off the front page, still, though
