### ISSUE TITLE
Speak to Evidence Base about how they will provide feedback through to the test user group

### ISSUE THREAD

**Issue by BexPerchard** [g4he/g4he#36]
Get in touch with Jo et al and decide how they will interact with user group, via me

**Comment by joeyanne** [comment]
@BexPerchard - likely to be the testers providing feedback to us on the value of the tools to them/their institution. As mentioned, we can schedule a call to discuss this, but it is likely to be us asking for volunteers (through you?) to speak to us, or possibly polling the group if there are simple evaluation questions we'd like to get a wider opinion on.
