### ISSUE TITLE
Poll test user group for times for initial skype meeting in June/July; orientation meeting

### ISSUE THREAD

**Issue by BexPerchard** [g4he/g4he#37]
Once got info from NJ, contact user group and send doodle poll for initial meeting.

**Comment by richard-jones** [comment]
In progress, dates still to be determined

**Comment by richard-jones** [comment]
Additional related tasks to this issue, based on today's sprint meeting:
- make an agenda and send it to the arma volunteers
- set up a google group for the project
- invite willian nixon to the test user group
