### ISSUE TITLE
Check if our indexing (in)efficiency causes problems for GtR

### ISSUE THREAD

**Issue by markmacgillivray** [g4he/g4he#47]
speak to GtR about how efficient they require our harvester to be; do we need to make it more efficient right now?

It may be beneficial to them to do some stress testing when we re-index

**Comment by richard-jones** [comment]
Have sent them an email to find out.  Awaiting response.

**Comment by richard-jones** [comment]
No response on this yet, so carrying over to next sprint as a task to monitor when there is time

**Comment by richard-jones** [comment]
No response after several weeks, so presuming there are no issues.
