### ISSUE TITLE
Look into frequency of source systems and gtr updates

### ISSUE THREAD

**Issue by markmacgillivray** [g4he/g4he#48]
We need to be able to state how often our source data is updated - how often does GtR update what we can pull? How often do their sources expose up to date data?

**Comment by njneilj** [comment]
From Louise:
Original Plan was initially for monthly updates to be rolled out at the first full release. This would be revised to shorter timeframes if the process allows. We may vary pulls from source systems in the future so for example we could accept Siebel and JES data on more regular basis. Source systems data changes vary as follows:
-  Grants Transaction system (Siebel) will depend on closing dates and start dates.  Essentially changes will occur daily. 
-  ROS.  Changes are as and when Researchers or admin staff submit data.  We expect any major push of information to correspond to specific encouragements from RC’s.  RC’s vary on the process followed but normally we would expect an outcome to be published a week or so after submission.
-  ResearchFish,  currently they do one trawl per year coinciding with the RC financial year end.  Data is then processed and would appear around end May-June.  They are looking to improve this process with a view to moving to more regular pulls and cleansing as a result of GtR.
-  Je-S/CDR – this is updated on demand by users and is a source for person and organisation information.
