### ISSUE TITLE
Create the application source repository and populate with base application framework

### ISSUE THREAD

**Issue by richard-jones** [g4he/g4he#56]
We need to make a new source repository (could be this one that the issue tracker is attached to) and create the basic application framework in it

**Comment by richard-jones** [comment]
- check this repo out
- add portality as upstream repository
- merge upstream
- push back here
- rename this repo to "g4he" and let the project team know

**Comment by markmacgillivray** [comment]
portality is up to date now, so once this repo is renamed you can pull it in no problem. Current G4HE demo is running purely off graphview for the moment, but can work that into the portality framework in following sprints.
