### ISSUE TITLE
Apply logos to all UK institutions

### ISSUE THREAD

**Issue by markmacgillivray** [g4he/g4he#60]
There is a list of them on wikipedia: 

http://en.wikipedia.org/wiki/List_of_universities_in_the_United_Kingdom

And for quite a lot of them the linked pages contain the logos.

There is also a service called logonoid.com where you can search and get some of the logos, and for any that are not on there a google image search for the logo of each university name would probably work.

If we can get all these logos in a folder (in our CL G4HE project folder) then we could use them for representing relationships between institutions, and as we are only using them to represent something about the institutions in question and they are publicly available advertisement logos, it should be OK under fair use.

**Comment by markmacgillivray** [comment]
Logos should be in jpg or png form, preferably all the same form if possible. Each logo should have a filename that is the actual name of the university to which it pertains, with _ between the words and no spaces. Care must be taken to ensure file names are correct, as this is what will be used to match the correct logo to searches. Capitalisation is unimportant. For example filename should be "the_university_of_edinburgh.jpg" - it does not matter if the words are capitalised or if the name starts with "the" or not.

**Comment by BexPerchard** [comment]
Ploughing through, have everything from the Wiki list up to Glyndwr Uni so far! Hoping to have them all by COB tomorrow :smile:

**Comment by markmacgillivray** [comment]
Excellent - where are they? Can you put the folder into our CL G4HE folder so I can start using them in the software?

**Comment by BexPerchard** [comment]
I have uploaded the folder with the logos so far to the G4HE one in our
Google drive - I'm afraid they are mostly .png,  but there are a few .jpegs
in there too as I couldn't find them in any other format. Is it easier if I
convert them for you or will it be OK?

I hope I've got all the names right too, let me know if I've missed
re-naming any! I'll get the others for you ASAP :D

Cheers,

Bex

On 28 June 2013 10:47, markmacgillivray notifications@github.com wrote:

> Excellent - where are they? Can you put the folder into our CL G4HE folder
> so I can start using them in the software?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/g4he/issuetracker/issues/60#issuecomment-20179313
> .

## 

_Rebecca Perchard_
Associate, Cottage Labs LLP

**Comment by markmacgillivray** [comment]
I can batch convert them to all be the same format later, so don't worry about that. Some of the file names still include the word "logo" though, so it would be useful if they could be renamed to only contain the words that are actually part of the university name, as then the matches should be better.

**Comment by markmacgillivray** [comment]
It would be good to have all of these by the time we announce next batch of functionality (next Monday). Then I could finish a nicer layout to the organisation page overviews.

**Comment by markmacgillivray** [comment]
@BexPerchard rather than just closing tasks like this one where there is follow-on work, add a comment that explains how you have completed your part then re-allocate it to whoever needs to work on it next.

In this case, please explain the current state of the logos and re-allocate to me for inclusion in the software if they are ready for that.

**Comment by markmacgillivray** [comment]
@BexPerchard please update the status of this and reassign once ready, I will work on this as soon as I return from holiday.

**Comment by richard-jones** [comment]
@BexPerchard - create a spreadsheet of all institutions, and their logos, and then confirm which ones aren't already there, and get any remaining ones

**Comment by BexPerchard** [comment]
@markmacgillivray here is a spreadsheet detailing that we have all of the logos https://docs.google.com/a/cottagelabs.com/spreadsheet/ccc?key=0AlF8Hy46rYEGdGNkOTJCd2JySzZUa3dpNHBNTF90Q3c#gid=0 they can all be found in the G4HE Logos folder in the G4HE google folder (internal), so you may now upload them as you please

**Comment by markmacgillivray** [comment]
We now have many duplicates, and quite a few logos not following the agreed naming convention., Re-assigning to Bex for analysis

**Comment by BexPerchard** [comment]
Logos have been checked and named appropriately. To the best of my knowledge I have caught all the duplicates and deleted. Reassigned to MM to apply to UI.

**Comment by BexPerchard** [comment]
Just to point out, I have collected logos for each separate school @ UAL. They are basically the main logo with the addition of the school name - use them if you want, or apply only the main UAL logo, I will leave that decision up to you.
