### ISSUE TITLE
tweaks needed to index structure

### ISSUE THREAD

**Issue by richard-jones** [g4he/g4he#69]
add relationship type to org records, for convenience in display

i.e.

```
{
    relationshipType : "Principal Investigator",
    ...
}
```

**Comment by richard-jones** [comment]
also, we may want to record LeadResearchOrganisation somewhere here too

**Comment by richard-jones** [comment]
we should also apply all the name canonicalisation to the primaryFunder field in the index too

**Comment by markmacgillivray** [comment]
Check at meeting if these are still required and if so add them when the index rebuild happens as per issue #130
