### ISSUE TITLE
New index has canonical people names with commas in them

### ISSUE THREAD

**Issue by markmacgillivray** [g4he/g4he#71]
Canonical names like "Jones, Richard" are annoying from the frontend handling perspective. It leads to splits at the comma, and then failure to match the names. This could be solved at the UI but I think it is better to tidy our canonical names instead.

Propose that names should be Firstname Lastname.

**Comment by richard-jones** [comment]
Note that the canonical names are used in the person selection mechanism in the benchmarking, so any changes here may require changes there

**Comment by markmacgillivray** [comment]
Changed the creation of canonical names in gtrindexer to not include commas
