### ISSUE TITLE
MRC places still exist

### ISSUE THREAD

**Issue by markmacgillivray** [g4he/g4he#72]
Although we have updated data, the MRC places that Gavin told us should not exist, still do. Our old data linked to GtR entities that were no longer there because our data was old, but now we still have links for these entities and they point into GtR to entities that DO still exist there - so it seems GtR have just changed their entity IDs.

http://gtr.rcuk.ac.uk/organisation/639B9787-DA6A-482B-9383-112F5A22BF03

**Comment by richard-jones** [comment]
No action required
