### ISSUE TITLE
Write blog post on how G4HE is going to help HEIs 

### ISSUE THREAD

**Issue by BexPerchard** [g4he/g4he#76]

**Comment by BexPerchard** [comment]
In light of more feedback from Valerie, I think the best way to approach this post is to use it as a way of engaging the sector and finding out what they would like; so say what we have done so far and how this may help. but ask for suggestions as to what they feel would be most helpful, rather than telling them.

**Comment by markmacgillivray** [comment]
Of course.

**Comment by richard-jones** [comment]
posted by bex
